In [2]:
import numpy as np 

In [3]:
arr = np.array([1,2,4,5,3,5,3,5,3,6,7,3])
arr


array([1, 2, 4, 5, 3, 5, 3, 5, 3, 6, 7, 3])

In [8]:
a = [3,4,3,3,5,3,23,2,3]
a

[3, 4, 3, 3, 5, 3, 23, 2, 3]

In [11]:
l = [[3,3,4,3,5],[3,344,3,345,3],[3,4,3,4,3]]

In [15]:
l

[[3, 3, 4, 3, 5], [3, 344, 3, 345, 3], [3, 4, 3, 4, 3]]

In [24]:
np.array(l)

array([[  3,   3,   4,   3,   5],
       [  3, 344,   3, 345,   3],
       [  3,   4,   3,   4,   3]])

In [26]:
    a        = np.zeros((4,6))
                                 arr  

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
arr = np.linspace (0,34,3)
arr

array([ 0., 17., 34.])