In [1]:
# <!-- Create a 1D NumPy array of numbers from 0 to 9 -->
import numpy as np 
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Write a code to convert a 1D array to a 2D array with 2 rows.
import numpy as np
arr = np.arange(8)
res = arr.reshape(2,4)
print(res)

[[0 1 2 3]
 [4 5 6 7]]


In [7]:
# Print Array Attributes

# Instructions: Print the following attributes of the array:

#     The shape of the array.
#     The number of array dimensions.
#     The size of each element in bytes.

import numpy as np  
arr = np.arange(7)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)


(7,)
1
8


In [8]:
#  Create a 3×3 NumPy array of all True
import numpy as np 
arr = np.full((3,3),True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
# Extract the documentation of NumPy’s arange() function
import numpy as np
arr = np.arange(5)
print(np.info(arr))

class:  ndarray
shape:  (5,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x63078a183f90
byteorder:  little
byteswap:  False
type: int64
None


In [10]:
# Create a 1D array filled with zeros and another filled with ones
import numpy as np 
o = np.ones(3)
z  = np.zeros(8)
print("zeros",z)
print("ones",o)

zeros [0. 0. 0. 0. 0. 0. 0. 0.]
ones [1. 1. 1.]


In [11]:
# Create a 1D array of 10 evenly spaced values between 5 and 50/
arr = np.arange(5,55,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [19]:
# Convert a Python list into a NumPy array
l = [1,2,3,2,4]
arr = np.array(l)
print(arr,type(arr))


[1 2 3 2 4] <class 'numpy.ndarray'>


In [28]:
#  Find the memory size of a NumPy array of numbers from 0 to 9
arr = np.arange(9)
s  = np.size(arr)
print(s)

9


In [30]:
# Reverse a 1D NumPy array
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [32]:
# Create a 3×3 identity matrix  Use tuple unpacking to swap the values of two variables without using a temporary variable.
z = np.zeros((3,3))
z[0,0]=1
z[1,1]=1
z[2,2]=1
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
#  Create a 4×4 array and extract its first row and last column
arr = np.arange(16)
raa = arr.reshape(4,4)
print(raa)
print('f=',raa[0])
print('f=',raa[:,-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
f= [0 1 2 3]
f= [ 3  7 11 15]


In [53]:
# Extract Odd Rows and Even ColumnsExtract an array of odd rows and even columns from below NumPy array.Problem BreakdownRows: In programming, indexing starts at 0. Odd-indexed rows would be rows 1 and 3.
# Columns: Even-indexed columns would be columns 0 and 2.
import numpy as np
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48], 
    [51, 54, 57, 60]
])

arr= sampleArray[1::2,::2]
print(arr)


[[15 21]
 [39 45]]


In [55]:
# Stack arrays horizontally
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.hstack((a,b))
print(arr)

[1 2 3 4 5 6]


In [70]:
arr = np.arange(16)
raa = arr.reshape(4,4)
print(raa)
a=raa[:2,:2]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [4 5]]
