In [8]:
# Slice the first two rows and first two columns from a 4×4 array
import numpy as np
arr = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

slice = arr[0:2,0:2]
print (slice)

[[1 2]
 [5 6]]


In [14]:
# Exercise 16: Replace all odd numbers in a NumPy array with -
arr = np.arange(11)
arr[arr % 2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [17]:
# Exercise 17: Get the indices of non-zero elements in an array/\
import numpy as np
arr = np.array([1, 0, 2, 0, 3, 0, 4])
non = np.nonzero(arr)
print(arr)

[1 0 2 0 3 0 4]


In [20]:
# Exercise 18: Find the common items between two arrays
import numpy as np

a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])
common = np.intersect1d(a,b)
print(common)

[2 4 8]


In [21]:
# Exercise 19: Perform arithmetic operations on two NumPy arrays element-wise
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum = a +b
multi = a*b
print ( sum , multi)

[5 7 9] [ 4 10 18]


In [22]:
# Write a code to compute the dot product of two NumPy arrays
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dt = np.dot(a,b)
print(dt)

32


In [24]:
# Compute the mean, median, and standard deviation of a NumPy array/
import numpy as np
arr = np.array([10, 20, 30, 100, 200, 300])
mean = np.mean(arr)
mod = np.std(arr)
med = np.median(arr)
print( arr , mean , mod , med)

[ 10  20  30 100 200 300] 110.0 107.08252269472673 65.0


In [31]:
# Exercise 22: Remove common items from array 
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
result   = a[~ np.isin(a,b)]
print(result)


[1 2]


In [32]:
# Exercise 24: Get the positions where elements of array a and b match
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])
re = np.where(a==b)
print(re)

(array([0, 2]),)


In [35]:
# Write a code to extract all numbers from an array that are between 5 and 10 (inclusive).
import numpy as np
arr = np.arange(15)
ap =arr[5:11]
print(ap)

[ 5  6  7  8  9 10]


In [38]:
# Exercise 26: Create a random 3×2 matrix and find its maximum and minimum values
arr = np.random.rand(3,2)
mx = np.max(arr)
mn = np.min(arr)
print (arr, mx ,mn)

[[0.67672169 0.02946991]
 [0.47289125 0.37839805]
 [0.9887994  0.68771711]] 0.9887994009362046 0.029469905817515296
