In [14]:
# Sorting a NumPy array based on a second column
import numpy as np
sam = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
sort_arr = sam[sam[:, 1].argsort()]

print(sort_arr)

[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [17]:
# Delete the second column from a given array and insert the following new column in its place.
import numpy as np

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumnToAdd = np.array([10, 10, 10])
dt = np.delete(sampleArray,1,axis=1)
ins = np.insert(dt,1,newColumnToAdd,axis=1)
print(sampleArray)
print(dt)
print(ins)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [21]:
# Exercise 29: Swap column 1 and 2 in a 2D array
import numpy as np
arr = np.arange(9).reshape(3, 3)
# The columns are at index 0, 1, 2. We want to rearrange to 0, 2, 1
print(arr)
arr[:,[1,2]] = arr[:,[2,1]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [25]:
# Exercise 30: Generate 10 random integers between 1 and 100
arr = np.arange(1,101,10)
print(arr)

[ 1 11 21 31 41 51 61 71 81 91]


In [27]:
# Exercise 31: Create a 3×3 array of random integers and sort it row-wise
arr = np.random.randint(1,50,size=(3,3))
srt = np.sort(arr)
print(arr)
print(srt)

[[44 45 14]
 [18 32 41]
 [10  8 24]]
[[14 44 45]
 [18 32 41]
 [ 8 10 24]]


In [29]:
# Shuffle an array randomly
arr = np.arange(10)
sf = np.random.shuffle(arr)
print(arr)

[6 5 0 3 2 4 7 8 1 9]


In [48]:
# Create a 5×5 2D array with 1s on the border and 0s inside.
arr = np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
# Exercise 34: Check if an array contains any NaN values.
import numpy as np
a = np.array([1, 2, np.nan, 4, 5])
k = np.isnan(a).any()
print(k)

True


In [56]:
# Exercise 35: Sort the rows of a 2D array based on the values of the second column
import numpy as np
arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])
srt = arr[:,1].argsort()
print(arr[srt])

[[5 2 7]
 [8 4 1]
 [6 9 3]]


In [59]:
# Write a code to Convert a 2D array into a 1D array
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
ar = arr.flatten()
print(ar)

[1 2 3 4 5 6]


In [62]:
# Exercise 37: Stack two arrays vertically and horizontally

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h = np.hstack((a,b))
v= np.vstack((a,b))
print(h,v)

[1 2 3 4 5 6] [[1 2 3]
 [4 5 6]]


In [ ]:
# Split a 1D array of 9 elements into 3 equal parts.
import numpy as np
arr = np.arange(9)
sp = np.split(arr,3)
print(arr)
print(sp)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [68]:
# Exercise 41: Use boolean indexing to filter values less than a given number
import numpy as np
arr = np.array([5, 12, 29, 30, 44, 7, 18])
print(arr[arr >30])

[44]


In [73]:
# Exercise 42: Count the number of occurrences of each unique element
import numpy as np
arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])
vals , counts = np.unique(arr,return_counts=True)
print(vals,counts)


[2 3 5] [3 3 2]


In [75]:
# Exercise 43: Find the intersection and union of two arrays
import numpy as np

a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

int = np.intersect1d(a,b)
un = np.union1d(a,b)
print(int , un)

[3 5 7] [1 2 3 4 5 6 7]


In [76]:
# Exercise 44: Transpose a matrix Transposing a matrix means flipping it over its diagonal
import numpy as np
arr = np.array([[1, 2], [3, 4]])
t = np.transpose(arr)
print(t)

[[1 3]
 [2 4]]
