In [1]:
import numpy as np

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [ ]:
# array sliesing 

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr  = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [37]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])